site_name: e-lims-core
site_url: https://fabienmeyer.github.io//e-lims-core
site_description: Cookiecutter template for e-lims projects
site_author: Fabien Meyer
site_dir: build
watch: [mkdocs.yml, docs, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md]

theme:
  name: material
  language: en
  features:
    - content.code.select
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css 

nav: # Setting up the navigation. Te below list will be tabs on left panel
  - Home: index.md
  - API: 
    - Utils:
      - DUT:
        - Trays: e_lims_core/utils/dut/trays.md
        - Device: e_lims_core/utils/dut/device.md
        - Export: e_lims_core/utils/dut/export.md
      - Files:
        - FileProps: e_lims_core/utils/files/file_props.md
        - Timestamp: e_lims_core/utils/files/timestamp.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ['e_lims_core']
          options:
            docstring_style: google
            members_order: source
            show_category_heading: false
            show_symbol_type_heading: true
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: true
              ignore_init_summary: false
            docstring_section_style: spacy
            merge_init_into_class: false
            show_if_no_docstring: false
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_classes: true
            show_docstring_module: true
            show_docstring_decriptions: true
            show_docstring_examples: true
            show_docstring_other_parameters: true
            show_docstring_raises: true
            show_docstring_recieves: true
            show_docstring_returns: false
            show_docstring_warns: true
            show_docstring_yields: true
  - privacy

extra:
  consent:
    cookies:
      analytics: Google Analytics
      github: GitHub 
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    copyright: >
      Copyright &copy; 2024 Fabien Meyer –
      <a href="#__consent">Change cookie settings</a>
    actions:
      - accept
      - reject
